# port apps
port: 2000

# Database
db: 
  host: localhost
  port: 3306
  user: farm
  pass: farm
  db: farm_express
  ssl: false
pool:
  min: 1
logFormat: default
logLevel: info

# server
ssl:
  enabled: false
  port: 2443
  provider: custom

  format: pem
  key: path/to/key.pem
  cert: path/to/cert.pem

bindIP: 0.0.0.0